# Use this for local testing of HTTPS functionality
version: "3.0.0"
service: "isame-lb-dev-https"

server:
  port: 8080
  https_port: 8443
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

upstreams:
  - name: "dev-backend"
    algorithm: "round_robin"
    backends:
      - url: "http://localhost:3000"
        weight: 1
      - url: "http://localhost:3001"
        weight: 1

health:
  enabled: true
  interval: "10s"
  timeout: "3s"
  path: "/health"
  unhealthy_threshold: 2
  healthy_threshold: 2

metrics:
  enabled: true
  port: 9090
  path: "/metrics"

circuit_breaker:
  enabled: true
  failure_threshold: 3
  timeout: "30s"

retry:
  enabled: true
  max_attempts: 2
  initial_backoff: "50ms"
  max_backoff: "500ms"

tls:
  enabled: true
  cert_file: "certs/dev/server.crt"
  key_file: "certs/dev/server.key"
  min_version: "1.2"
