# dev config
version: "1.0.0"
service: "isame-lb-dev"

server:
  port: 8080

upstreams:
  - name: "dev-backend"
    algorithm: "round_robin"
    backends:
      - url: "http://localhost:8081"
        weight: 1
      - url: "http://localhost:8082"
        weight: 1

health:
  enabled: true
  interval: "10s"
  timeout: "3s"
  path: "/health"

metrics:
  enabled: true
  port: 9090
